openapi: 3.0.3

info:
  title: Payments API
  version: 1.0.0

paths:
  /payments:
    get:
      summary: List payments
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transaction_id:
                      type: string
                    status:
                      type: string
