apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: nginx:1.27
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
